@startuml
enum LogLevel{
    FATAL,
    ERROR,
    WARN,
    INFO,
    DEBUG;
}

class Logger{
     String name;
     LogLevel logLevel;
     List<SinkAppender> appends;
     public void writeAppender(String message, LogLevel level)'
}

class LoggerConfiguration {
    List<Logger> loggers;
}

interface LoggerService {
    void log(String message, LogLevel level);
}

abstract class SinkAppender {
    SinkType sinkType;
    String timeFormat;
    public abstract void write(String message);
}


class DatabaseAppender extends SinkAppender{
    String host;
    String username;
    String password;
}

class FileAppender extends SinkAppender{
    String filePath;
}

class ConsoleAppender extends SinkAppender{

}

enum SinkType{
    File,
    Database,
    Console
    TextFile;

}

@enduml