@startuml
'https://plantuml.com/class-diagram

interface LoggerService{
    void info(String message);
    void fatal(String message);
    void error(String message);
    void warn(String message);
    void debug(String message);
}

class Logger{



@enduml